project_name: go-logkeycheck

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - freebsd
    ldflags:
      - -s -w -X main.version={{.Version}}+{{.ShortCommit}} -X main.date={{.Date}}
    binary: "go-logkeycheck"

archives:
  - format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
